NGコマンドの文字列処理の方法を変更
SSW-SCIENTIFIC/NNDD pull request #4
Opened 2017-09-28 02:53 UTC by kurotoris

前のPRの停止ありがとうございます
今回は速度はほんの少し落ちてる気がする程度で済んでいます
あと、NGコマンドの文字処理にsearch()を使用することで正規表現に対応させました

変更点としては下記のようになります
NGListManagerの最初の方に　ngCommandAll（ALL用フラグ）　ngCommandList（NGコマンドリスト）　の宣言をしました
refreshNgMap　をかなり変更しました
NGコマンドに"ALL"の文字列があるかどうか確認し、あった場合は　ngCommandAll　にtrueを設定する
NGコマンド文字列を　ngCommandList　に放り込む処理をする
これに伴いNGコマンド文字列は　NgMap　には入れていません
isNgCommand　は　ngCommandAll　にtrueが設定されている場合には"184"などのコマンドを含むかの判断をさせる
"184"コマンドは"DEVICE:3DS"など類似コマンドもあるので、受け取ったコマンドを切り分けてチェックをかけている
その処理が終了した後　ngCommandList　に入っているNGコマンドコマンド文字列とコマンド文字列を正規表現で比較し処理する
正規表現での検索に対応してる事を動作確認済み

という感じに変更しました
大きな変更点の部分は、修正前の処理を一応残すようにしました
前回と同じように、私の変更点には日付を横に書いてあります

処理自体は、処理するコメント数が１万以上まで多くなると、微妙に差が出てる気がしますが
元のプログラムと１秒あるかないかの差の上に、全体的な動画読み込みの中に埋もれてしまうので
今回の処理は問題ないと思います

2017-09-28 12:15 UTC, SSW-SCIENTIFIC commented on src/org/mineap/nndd/player/NGListManager.as
> +			}
正規表現より`Command2.indexOf(ngCommand) != -1`で判定した方がよいと思います(正規表現は非常に遅い)。
ただ微妙なところもある(コマンドの一部を拾ってしまう可能性がある)ので正規表現とするなら`new RegExp("\\b" + ngCommand + "\\b", "i")`をパターンとして使った方がいいでしょう(処理速度と正確性のトレードオフです)。

ただNgCommandListを本当にAll ofで処理するのならば`var commands = Command2.split(" ")`及び`var ngCommands = ngCommand.split(" ")`として`in commands`と`in ngCommands`の2重ループを回すのが適切かなと思います。
`ngCommands.length == 1`の場合だけ上記の`indexOf`による判定にすれば, 実際のNG登録で2重ループで判定しなければならないケース(複数コマンドのAll of 判定)は殆どないはずなので, 速度的な影響も少ない気がします。

2017-09-30 09:05 UTC, kurotoris commented on src/org/mineap/nndd/player/NGListManager.as
> +			}
ＮＧコマンドの被りでueとbl"ue”が被ってる事が分かりました
ちょっと解決方法考えて、出来たら修正かけます

2017-09-30 11:42 UTC, SSW-SCIENTIFIC commented on src/org/mineap/nndd/player/NGListManager.as
> +			}
```actionscript
var CommandList = Command2.split(" ");
var ngCommandList = ngCommand.split(" ");
var result = true;

for each(var command in CommandList) {
    if (ngCommandList.indexOf(command) == -1) {
        result = false;
    }
}
```

試してませんがこんなのはどうでしょうか。

2017-10-06 23:49 UTC, SSW-SCIENTIFIC requested changes
修正提案
----------
`ue big`と`big ue`とで同じ結果が得られないのはやはり残念なので, 248-255行目を以下のように変更することを提案します。

```actionscript
var commands: Array = Command2.split(" ");
for each(var ngCommand:String in ngCommandList){
    var ngCommands: Array = ngCommand.split(" ");
    var matched: Boolean = true;

    for each (var ngItem: String in ngCommands) {
        if (commands.indexOf(ngItem) === -1) {
            matched = false;
            break;
        }
    }

    if (matched) {
        return true;
    }
}

return false;
```

`ngCommandList`に対してはAny ofで処理を行い, その中の各`ngCommand`は`split`で分割した上で`Command2`に全てが含まれるかを検査します。

処理速度
---------
sm116203でテストしました。
上記修正後, 200コメント/分の表示設定で`ue red`, `big red`などの処理時間は概ね100ms未満でフィルタリング出来ています(件数が増える場合は線型増加だと思われる)
修正前の正規表現を利用したコードでは, 内容にも依りますが100-200ms程度の処理時間であったため, 正規表現よりも`indexOf`による判定の方がよいと判断します。

2017-10-06 23:51 UTC, SSW-SCIENTIFIC submitted a review, later dismissed

2017-10-09 11:47 UTC, kurotoris commented
提案のあった通りに書き換えました
一部、元から　split　処理をしている場所があるので
そちらで　split　処理をする状態に書き直しました
こちらでもNG処理のチェックをしましたが、問題ありませんでした

色々と教えていただいたり、お手間を取らせて申し訳ないです
ありがとうございました

2017-10-09 12:39 UTC, SSW-SCIENTIFIC approved these changes
お疲れさまでした。マージします。

2017-10-09 12:39 UTC, merged